force-app/main/default/objects/Item__c/Item__c.object-meta.xml
<CustomObject>
    <label>Item</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Item__c/fields/Milestone__c.field-meta.xml
<CustomField>
    <fullName>Milestone__c</fullName>
    <label>Milestone</label>
    <referenceTo>Milestone__c</referenceTo>
    <relationshipLabel>To-do Items</relationshipLabel>
    <relationshipName>Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Status of the item</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Status_Values</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Milestone__c/Milestone__c.object-meta.xml
<CustomObject>
    <label>Milestone</label>
    <nameField>
        <label>Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Milestone__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipLabel>Milestones</relationshipLabel>
    <relationshipName>Milestones</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Milestone__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( Progress__c  = 0, &apos;Not Started&apos; ,  IF(Progress__c &gt;= 1, &apos;Complete&apos;, &apos;In Progress&apos;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <formula>IF( Progress__c = 0, &apos;Not Started&apos; , IF(Progress__c &gt;= 1, &apos;Complete&apos;, &apos;In Progress&apos;) )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Status</label>
    <type>Text</type>
</CustomField>

force-app/main/default/globalValueSets/Status_Values.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Not Started</fullName>
        <default>true</default>
        <label>Not Started</label>
    </customValue>
    <customValue>
        <fullName>In Progress</fullName>
    </customValue>
    <customValue>
        <fullName>Complete</fullName>
    </customValue>
    <masterLabel>Status Values</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/ProjectCreatorController.cls
public with sharing class ProjectCreatorController {
    @AuraEnabled(cacheable=false)
    public static Id createProject(String projectName, String milestones) {
        try {
            Project__c project = new Project__c(Name = projectName);
            insert project;

            if (project.Id != null && milestones != null) {
                List<MilestoneWrapper> milestonesWrapper = (List<MilestoneWrapper>)JSON.deserialize(
                    milestones,
                    List<MilestoneWrapper>.class
                );

                List<Milestone__c> milestoneList = new List<Milestone__c>();
                for (MilestoneWrapper milestone : milestonesWrapper) {
                    Milestone__c newMilestone = new Milestone__c(
                        Name = milestone.name,
                        Project__c = project.Id
                    );
                    milestoneList.add(newMilestone);
                }

                insert milestoneList;

                List<Item__c> itemList = new List<Item__c>();
                Integer iterator = 0;
                for (MilestoneWrapper milestone : milestonesWrapper) {
                    if (milestone.items != null) {
                        for (ItemWrapper item : milestone.items) {
                            Item__c newItem = new Item__c(
                                Name = item.name,
                                Status__c = item.status,
                                Milestone__c = milestoneList[iterator].Id
                            );
                            itemList.add(newItem);
                        }
                    }
                    iterator ++;
                }
                insert itemList;
            }
            
            return project.Id;
        } catch (Exception ex) {
            throw new AuraHandledException('Error creating Project: ' + ex.getMessage());
        }
    }

    @AuraEnabled(cacheable=false)
    public static Id createMilestones(Id projectId, String milestoneReq) {
        try {
            if (projectId != null) {
                MilestoneWrapper milestoneWrapper = (MilestoneWrapper) JSON.deserialize(
                    milestoneReq,
                    MilestoneWrapper.class
                );

                Milestone__c newMilestone = new Milestone__c(
                    Name = milestoneWrapper.name,
                    Project__c = projectId
                );

                insert newMilestone;

                if (milestoneWrapper.items.size() > 0) {
                    List<Item__c> itemList = new List<Item__c>();
                    for (ItemWrapper item : milestoneWrapper.items) {
                        Item__c newItem = new Item__c(
                            Name = item.name,
                            Status__c = item.status,
                            Milestone__c = newMilestone.Id
                        );
                        itemList.add(newItem);
                    }
                    insert itemList;
                }
                
                return newMilestone.id;
            }
            return null;
        } catch (Exception ex) {
            throw new AuraHandledException('Error creating Milestones: ' + ex.getMessage());
        }
    }

    @AuraEnabled(cacheable=false)
    public static Id createItem(Id milestoneId, String itemReq) {
        try {
            if (milestoneId != null && itemReq != null) {
                ItemWrapper itemWrapper = (ItemWrapper) JSON.deserialize(
                    itemReq,
                    ItemWrapper.class
                );
                Item__c newItem = new Item__c(
                    Name = itemWrapper.name,
                    Status__c = itemWrapper.status,
                    Milestone__c = milestoneId
                );
                insert newItem;
                return newItem.Id;
            }
            return null;
        } catch (Exception ex) {
            throw new AuraHandledException('Error creating Items: ' + ex.getMessage());
        }
    }

    public class MilestoneWrapper {
        @AuraEnabled public String name;
        @AuraEnabled public List<ItemWrapper> items;
    }

    public class ItemWrapper {
        @AuraEnabled public String name;
        @AuraEnabled public String status;
    }
}